version: "3"

tasks:
  default:
    desc: List all tasks
    cmd: task --list-all

  build:
    cmds:
      - go build -o bin/devbox . && sudo mv bin/devbox /usr/bin/

  docker:build:
    cmds:
      - docker build -t firmotecnologia/devbox:latest ./docker

  docker:push:
    deps:
      - docker:build
    cmds:
      - docker push firmotecnologia/devbox:latest

  dev:
    cmds:
      - task: docker:push
      - task: build
